//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BankUI.rc
//
#define IDOK2                           2
#define IDR_MAINFRAME                   100
#define IDI_ICON_BAIDU                  133
#define IDI_ICON_GOOGLE                 134
#define IDI_ICON_SOGOU                  135
#define IDR_MENU_HELP                   137
#define IDD_DIALOG_ABOUT                138
#define IDD_DIALOG_SETTING              139
#define IDD_DIALOG_SECUCHECK            142
#define IDI_ICON1                       143
#define IDD_DIALOG_INSTALLCHECK         144
#define IDD_DIALOG_AUTHEN               150
#define IDD_DIALOG_TIPS                 151
#define IDD_DIALOG_MSGBOX               152
#define IDD_DIALOG_FILEDOWNLOAD         153
#define IDD_DIALOG_DOWNLOADOPTION       154
#define IDD_DIALOG_DOWNLOADPROGRESS     155
#define IDR_MENU1                       156
#define IDD_DIALOG_SAVEFAV_PROGRESS     157
#define IDD_DLG_MENU                    158
#define IDD_DIALOG1                     159
#define IDD_DLG_BILL_SELECT             159
#define IDD_SELECT_MONTH                160
#define IDD_DIALOG_SYNCHRO              161
#define IDI_ICON_VIDEO                  200
#define IDC_CHECK_AUTORUN               1163
#define IDC_CHECK_STRICTFILTER          1164
#define IDC_CHECK_STRICTURL             1164
#define IDC_PROGRESS1                   1164
#define IDC_STATIC_FILENAME             1165
#define IDC_STATIC_FILENAME2            1166
#define IDC_EDIT_PWD                    1167
#define IDC_EDIT_INFORMATION            1167
#define IDC_EDIT_LINE1                  1167
#define IDC_EDIT_LINE3                  1168
#define IDC_EDIT_LINE2                  1169
#define IDC_EDIT_DELPWD                 1170
#define IDC_CHECK1                      1171
#define IDC_EDIT_DELPWD2                1171
#define IDC_NEXTPAGE                    1172
#define IDC_PREPAGE                     1173
#define IDC_MESSAGE_SHOW                1174
#define IDC_TABCTRL                     1174
#define IDB_BITMAP_SHOW                 1175
#define IDC_STATIC_TITLE                1176
#define IDC_GUIDE                       1177
#define IDC_RADIO_REMINDER_YES          1178
#define IDC_RADIO_REMINDER_NO           1179
#define IDC_RADIO_UPDATE_YES            1180
#define IDC_RADIO_UPDATE_NO             1181
#define IDC_RADIO_PASSWORD_YES          1182
#define IDC_RADIO_PASSWORD_NO           1183
#define IDC_STATIC_LINE1                1184
#define IDC_TEXT_PASSWORD_YES           1185
#define IDC_STATIC_LINE2                1186
#define IDC_STATIC_LINE3                1187
#define IDC_STATIC_DELPWD               1188
#define IDC_PWD_LOST                    1189
#define IDC_TEXT_UPDATE_NO              1189
#define IDC_SYSCLOSE                    1190
#define IDC_BUTTON_1                    1191
#define IDC_TEXT_PASSWORD_NO            1191
#define IDC_BUTTON_2                    1192
#define IDC_TEXT_UPDATE_YES             1192
#define IDC_BUTTON_3                    1193
#define IDC_TEXT_REMINDER_NO            1193
#define IDC_BUTTON_4                    1194
#define IDC_STATIC_CURPWD2              1194
#define IDC_TEXT_REMINDER_YES           1194
#define IDC_SAVE                        1194
#define IDC_OPEN                        1195
#define IDC_STATIC_URL                  1196
#define IDC_STATIC_PROGRESS             1197
#define IDC_STATIC_STATUS               1198
#define IDC_COMPANY_ICON                1199
#define IDC_STATIC_UNKNOWNLENGTH        1201
#define IDC_LIST_VERSION                1205
#define IDC_STATIC_PART_FRONT           1206
#define IDC_STATIC_PART_BEHIND          1207
#define IDC_BTN_MAIL_CHANGE             1209
#define IDC_BTN_PW_CHANGE               1210
#define IDC_STATIC_MAIL_SHOW            1211
#define IDC_STATIC_PW_SHOW              1212
#define IDC_FRAME_FRONT                 1214
#define IDC_FRAME_BEHIND                1215
#define IDC_STATIC_NEW_MAIL             1216
#define IDC_BTN_SURE_CHANGE             1217
#define IDC_CHECK_PW                    1218
#define IDC_CHECK_AUTO                  1219
#define IDC_CHECK_UN                    1220
#define IDC_BTN_CLEAN                   1221
#define IDC_STATIC_CLEAN_INFO           1222
#define IDC_STATIC_INFO                 1223
#define IDC_CHECK_SECCION               1225
#define IDC_EDIT_TIME                   1227
#define IDC_STATIC_CLENLOAD             1228
#define IDC_STATIC_CLEANLOAD            1228
#define IDC_STATIC_QUITLOAD             1229
#define IDC_BUTTON1                     1230
#define IDC_BUTTONsyn                   1230
#define IDC_PROGRESS_SYNCHRO            1231
#define IDC_DATETIMEPICKER1             1232
#define IDC_STATICD                     1232
#define IDC_STATICS                     1232
#define IDC_DATETIMEPICKER2             1233
#define IDC_STATIC_UNKNOWNLENGTHS       1233
#define IDC_SYSLINK1                    1234
#define IDC_STATIC_FILENAMES            1234
#define IDC_SYSLINK2                    1235
#define IDC_STATIC_STATUSS              1235
#define IDC_SYSLINK3                    1236
#define IDC_RESOURCE                    1236
#define IDC_SYSLINK4                    1237
#define IDC_CALLBACKLIST                1237
#define IDC_STATIC1                     1238
#define IDC_SYSLINK5                    1239
#define IDC_STATIC2                     1240
#define IDC_BUTTON2                     1240
#define ID_HELP_ABOUT                   33065
#define ID_HELP_UPDATE                  33066
#define ID_HELP_SETTING                 33069
#define ID_HELP_FEEDBACK                33070
#define ID_HELP_TIPS                    33075
#define ID_HELP_PASSWORD                33076
#define ID_HELP_33077                   33077
#define ID_III                          33078
#define ID_III_UUUU                     33079
#define ID_HELP_000                     33080

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         33081
#define _APS_NEXT_CONTROL_VALUE         1241
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
