del ..\Release\syslog.txt
del ..\Release\*.map
del ..\Release\*.lib
del ..\Release\*.pdb
del ..\Release\*.ilk
del ..\Release\*.ilk
del ..\Release\*.exp
del ..\Release\BankLoaderTester.exe
del ..\Release\DigsigGen.exe
del ..\Release\ModuleVerifierTester.exe
del ..\Release\LogManager.dll
del ..\Release\VerifyList.xml
del ..\Release\BankActiveXTest.html
del ..\Release\MoneyHub.chk
del ..\Release\BankInfo\info.chk
.\Release\MakeCHK.exe ..\Release