del ..\Debug\syslog.txt
del ..\Debug\*.map
del ..\Debug\*.lib
del ..\Debug\*.pdb
del ..\Debug\*.ilk
del ..\Debug\*.ilk
del ..\Debug\*.exp
del ..\Debug\BankLoaderTester.exe
del ..\Debug\DigsigGen.exe
del ..\Debug\ModuleVerifierTester.exe
del ..\Debug\LogManager.dll
del ..\Debug\VerifyList.xml
del ..\Debug\BankActiveXTest.html
del ..\Debug\MoneyHub.chk
del ..\Debug\BankInfo\info.chk
del ..\Debug\SystemDB.exe
.\Debug\EncryptJSFile.exe ..\Debug
.\Debug\MakeCHK.exe ..\Debug